# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_odds', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('team2_odds', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('datetime', models.DateTimeField()),
                ('finished', models.BooleanField(default=True)),
                ('valid', models.BooleanField(default=True)),
                ('bestof', models.IntegerField(default=1)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_team1', to='app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_team2', to='app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_as_winner', to='app.Team'),
        ),
    ]
